version: '3.9'  # Docker Compose version

services:
  # Backend service 
  flask-app:
    container_name: flask-app
    build: src # from dockerfile in src directory
    links:
      - mysql-db  # Link the Flask app container to MySQL container
    ports:
      - "5001:5000"  # Map Flask app port 
    volumes:
      - ./src:/app  # Mount your source code directory to /app inside container
      - ./data:/data  # Mount your source code directory to /app inside container
    depends_on:
      - mysql-db


  mysql-db:
    volumes:
      - ./mysql_db/custom.cnf:/etc/mysql/conf.d/custom.cnf # Custom MySQL configuration file
      - ./mysql_db:/docker-entrypoint-initdb.d/:ro # runs all .sql script from docker entrypoint on container creation
      - ./data:/data  # Mount data directory to /data/csv inside container
      - ./data:/var/lib/mysql-files  # Mount data directory to /data/csv inside secure_file_priv of mysql container
      - mysql-data:/var/lib/mysql # persist data
    restart: always
    command: 
      - '--local-infile=1' # Enable local infile

volumes:
  mysql-data: